### ISSUE TITLE
归档为空

### ISSUE THREAD

**Issue by C860** [hhqcontinue/hhqcontinue.github.io#1]
归档根本没看到文章，这个BUG修复一下。

另外UI也优化一下，好丑，哈哈，不过能坚持写博文真心不错，我都好久没写博客了。

**Comment by hhqcontinue** [comment]
好的，谢谢建议。

嗯嗯，我也希望能坚持下去。大家加油！

**Comment by hhqcontinue** [comment]
有空经过看到有什么写得不好的也说说呀。谢谢哦。

**Comment by C860** [comment]
没问题，要不要我帮你的博客做个主题呀嘿嘿，我最近的设计能力还是提升了不少的哦！

**Comment by hhqcontinue** [comment]
好呀，感激不尽！！你有空的时候帮我做做哦，做好发我看看
